FROM golang:1.14.3-alpine3.11 as builder
RUN apk add --no-cache git
WORKDIR /home
COPY ./ .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE="auto" \
	go build -o dashboard cmd/dashboard/main.go

FROM gcr.io/distroless/static
WORKDIR /app/
COPY --from=builder /home/dashboard .
ENTRYPOINT ["/app/dashboard"]
